// Public brand files only. Never turn this into a directory/file-path endpoint.
export const BRAND_ASSETS = Object.freeze({
  // Original Autonom workbench and scoped product presentation.
  '/product.css': 'product.css',
  '/product-home.css': 'product-home.css',
  '/product-home.js': 'product-home.js',
  '/product-copy.mjs': 'product-copy.mjs',
  '/cinema-copy.mjs': 'cinema-copy.mjs',
  '/studio-copy.mjs': 'studio-copy.mjs',
  '/product-discovery.css': 'product-discovery.css',
  '/product-launch.css': 'product-launch.css',
  '/product-room.css': 'product-room.css',
  '/product-docs.css': 'product-docs.css',
  '/autonom-world.js': 'autonom-world.js',
  '/autonom-world.css': 'autonom-world.css',
  '/home-discovery.js': 'home-discovery.js',
  '/brand/studio/geist-variable.woff2': 'brand/studio/geist-variable.woff2',
  '/brand/studio/Geist-OFL.txt': 'brand/studio/Geist-OFL.txt',
  '/brand/cinema/barlow-condensed-700.woff2': 'brand/cinema/barlow-condensed-700.woff2',
  '/brand/cinema/barlow-condensed-800.woff2': 'brand/cinema/barlow-condensed-800.woff2',
  '/brand/cinema/BarlowCondensed-OFL.txt': 'brand/cinema/BarlowCondensed-OFL.txt',

  '/metahuman-brand.css': 'metahuman-brand.css',
  '/reference.css': 'reference.css',
  '/autonom.css': 'autonom.css',
  '/autonom-shell.js': 'autonom-shell.js',
  '/explore.js': 'explore.js',
  '/explore-model.mjs': 'explore-model.mjs',
  '/explore-i18n.mjs': 'explore-i18n.mjs',
  '/stream-previews.js': 'stream-previews.js',
  '/room-chat.js': 'room-chat.js',
  '/chat-motion.js': 'chat-motion.js',
  '/wallet-proposals.js': 'wallet-proposals.js',
  '/launch-layout.css': 'launch-layout.css',
  '/launch-layout.js': 'launch-layout.js',
  '/brand/reference/inter-400.woff2': 'brand/reference/inter-400.woff2',
  '/brand/reference/inter-500.woff2': 'brand/reference/inter-500.woff2',
  '/brand/reference/inter-600.woff2': 'brand/reference/inter-600.woff2',
  '/brand/reference/Inter-OFL.txt': 'brand/reference/Inter-OFL.txt',
  // Type since 2026-09-24: Space Grotesk (display) + Manrope (reading), SIL OFL, licenses alongside.
  '/brand/fonts/space-grotesk-latin.woff2': 'brand/fonts/space-grotesk-latin.woff2',
  '/brand/fonts/space-grotesk-latin-ext.woff2': 'brand/fonts/space-grotesk-latin-ext.woff2',
  '/brand/fonts/manrope-latin.woff2': 'brand/fonts/manrope-latin.woff2',
  '/brand/fonts/manrope-latin-ext.woff2': 'brand/fonts/manrope-latin-ext.woff2',
  '/brand/fonts/SpaceGrotesk-OFL.txt': 'brand/fonts/SpaceGrotesk-OFL.txt',
  '/brand/fonts/Manrope-OFL.txt': 'brand/fonts/Manrope-OFL.txt',
  '/favicon.ico': 'brand/favicon-32.png',
  '/brand/autonom-mark.png': 'brand/autonom-mark.png',
  '/brand/favicon-32.png': 'brand/favicon-32.png',
  '/brand/apple-touch-icon.png': 'brand/apple-touch-icon.png',
  '/brand/autonom-social.jpg': 'brand/autonom-social.jpg',
  '/brand/desktop-wallpaper.png': 'brand/desktop-wallpaper.png',
  '/brand/autonom-space-v2-1280.webp': 'brand/autonom-space-v2-1280.webp',
  '/brand/autonom-space-v2-2560.webp': 'brand/autonom-space-v2-2560.webp',
  '/brand/autonom-space-v2-3840.webp': 'brand/autonom-space-v2-3840.webp',
});
